// <auto-generated />
using System;
using GreenShadow.Blog.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GreenShadow.Blog.DataAccess.Data.Blog
{
    [DbContext(typeof(BlogContext))]
    [Migration("20190922085457_InitialBlogModel")]
    partial class InitialBlogModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GreenShadow.Blog.Domain.Models.Article", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArticleCommentCount");

                    b.Property<DateTime>("ArticleDate");

                    b.Property<int>("ArticleLikeCount");

                    b.Property<int>("ArticleViews");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
