version: '3.4'

services:
  verdure.content.api:
    image: ${DOCKER_REGISTRY-}verdurecontentapi
    build:
      context: .
      dockerfile: src/Services/Content/Verdure.Content.Api/Dockerfile

  verdure-content-api-dapr:
    image: "daprio/daprd:1.5.1"
    network_mode: "service:verdure.content.api"
    depends_on:
      - verdure.content.api

  mongodb:
    image: mongo

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim

  verdure.ui.blazor:
    image: ${DOCKER_REGISTRY-}verdureuiblazor
    build:
      context: .
      dockerfile: src/UI/Verdure.UI.Blazor/Dockerfile

  verdure.reviews.api:
    image: ${DOCKER_REGISTRY-}verdurereviewsapi
    build:
      context: .
      dockerfile: src/Services/Reviews/Verdure.Reviews.Api/Dockerfile


  verdure.admin.api:
    image: ${DOCKER_REGISTRY-}verdureadminapi
    build:
      context: .
      dockerfile: src/Services/Admin/Verdure.Admin.Api/Dockerfile

  verdure-admin-api-dapr:
    image: "daprio/daprd:1.5.1"
    network_mode: "service:verdure.admin.api"
    depends_on:
      - verdure.admin.api

  verdure.ui.blazor.product:
    image: gilzhang/verdure-blazor-ui

