apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: verdure-secretstore
  namespace: verdure
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /components/verdure-secrets.json
  - name: nestedSeparator
    value: "."
